FROM alpine:3.9

# set some defaults
ENV AWS_ACCESS_KEY_ID AKIA6GR4N6RF2ND3RS6Z
ENV AWS_SECRET_ACCESS_KEY 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
ENV AWS_DEFAULT_REGION us-east-1

COPY install.sh /opt/install.sh
RUN /opt/install.sh

CMD bash
